# Generated by Django 3.1.5 on 2021-01-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='interests_and_hobbies',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='program_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_biography',
            field=models.TextField(max_length=500),
        ),
    ]
